# .github/workflows/build-release.yml

name: Build and Release APK

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload APK to GitHub Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.release.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: maatran-release.apk
          asset_content_type: application/vnd.android.package-archive
